<?php
// module/Album/view/album/album/index.phtml:

$title = 'Categorias';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a class="btn btn-success" href="<?php echo $this->url('album', array('action' => 'add')); ?>">Add new album</a>
</p>

<table class="table table-bordered">
    <tr>
        <th>Titulo</th>
        <th>Descrição</th>
        <th>Ações</th>
    </tr>
    <?php foreach ($categorias as $album) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($album->categoria_nome); ?></td>
            <td><?php echo $this->escapeHtml($album->categoria_descricao); ?></td>
            <td>
                <a class="btn btn-primary" href="<?php echo $this->url('album', array('action' => 'edit', 'id' => $album->categoria_id));
    ?>">Edit</a>
                <a class="btn btn-danger" href="<?php echo $this->url('album', array('action' => 'delete', 'id' => $album->categoria_id));
    ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>